<a href="https://colab.research.google.com/github/ShibleNK/pandas-in-python/blob/main/pandas_tutorials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

Get dataset

In [2]:
df = pd.read_csv("/content/drive/MyDrive/property_listing_data_in_Bangladesh.csv")
df_1 = pd.read_csv("/content/drive/MyDrive/archive/heart_disease_uci.csv")

In [3]:
df

,title,beds,bath,area,adress,type,purpose,flooPlan,url,lastUpdated,price
0,Eminent Apartment Of 2200 Sq Ft Is Vacant For ...,3,4,"2,200 sqft","Block A, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"August 13, 2022",50 Thousand
1,"Apartment Ready To Rent In South Khulshi, Near...",3,4,"1,400 sqft","South Khulshi, Khulshi, Chattogram",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/44...,https://www.bproperty.com/en/property/details-...,"January 25, 2022",30 Thousand
2,"Smartly priced 1950 SQ FT apartment, that you ...",3,4,"1,950 sqft","Block F, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/11...,https://www.bproperty.com/en/property/details-...,"February 22, 2023",30 Thousand
3,2000 Sq Ft Residential Apartment Is Up For Ren...,3,3,"2,000 sqft","Sector 9, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/14...,https://www.bproperty.com/en/property/details-...,"October 28, 2021",35 Thousand
4,Strongly Structured This 1650 Sq. ft Apartment...,3,4,"1,650 sqft","Block I, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"February 19, 2023",25 Thousand
...,...,...,...,...,...,...,...,...,...,...,...
7552,"Picture Yourself, Residing In This Well Constr...",4,4,"3,600 sqft","Sector 3, Uttara, Dhaka",Duplex,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",80 Thousand
7553,Flat For Rent In Uttara Sector 13 Near Lubana ...,3,2,900 sqft,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 9, 2022",19 Thousand
7554,1000 SQ FT flat for rent in Uttara Sector 13 n...,2,2,"1,000 sqft","Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/12...,https://www.bproperty.com/en/property/details-...,"February 14, 2022",22 Thousand
7555,Well Planned Apartment For Rent In Gulshan 1 N...,3,4,"3,600 sqft","Gulshan 1, Gulshan, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/30...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",1.75 Lakh
7556,An Apartment Is Ready For Rent At Baridhara DO...,4,4,"2,600 sqft","Baridhara DOHS, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"November 22, 2021",90 Thousand

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7557 entries, 0 to 7556
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        7557 non-null   object
 1   beds         7557 non-null   object
 2   bath         7557 non-null   object
 3   area         7557 non-null   object
 4   adress       7557 non-null   object
 5   type         7557 non-null   object
 6   purpose      7557 non-null   object
 7   flooPlan     7556 non-null   object
 8   url          7557 non-null   object
 9   lastUpdated  7557 non-null   object
 10  price        7557 non-null   object
dtypes: object(11)
memory usage: 649.6+ KB

In [ ]:
df['sex'] = df['sex'].map({'Male':1, 'Female':0})

In [ ]:
df

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,1,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,1,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,1,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,1,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,0,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,54,0,VA Long Beach,asymptomatic,127.0,333.0,True,st-t abnormality,154.0,False,0.0,NaN,NaN,NaN,1
916,917,62,1,VA Long Beach,typical angina,NaN,139.0,False,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,0
917,918,55,1,VA Long Beach,asymptomatic,122.0,223.0,True,st-t abnormality,100.0,False,0.0,NaN,NaN,fixed defect,2
918,919,58,1,VA Long Beach,asymptomatic,NaN,385.0,True,lv hypertrophy,NaN,NaN,NaN,NaN,NaN,NaN,0
919,920,62,1,VA Long Beach,atypical angina,120.0,254.0,False,lv hypertrophy,93.0,True,0.0,NaN,NaN,NaN,1

In [4]:
import re

def price_processor(row):
  thousand = 1000
  lakh = 100000
  if 'Thousand' in row:
    return float(re.sub(r'[\s]|Thousand|thousand','', row)) * thousand

  return float(re.sub(r'[\s]|Lakh|thousand','', row)) * lakh



def string_processor(input_string):

  return int(re.sub(r'[,\s]|sqft', "", input_string)
)

In [5]:
df['price'] = df['price'].apply(price_processor)
df['area'] = df['area'].apply(string_processor)

df['beds'] = df['beds'].str.replace(' Bed','').astype('int')
df['bath'] = df['bath'].str.replace(' Bath','').astype('int')

df['city'] = df['adress'].apply(lambda x: 'Dhaka' if 'Dhaka' in x else 'Chattogram')

In [6]:
df

,title,beds,bath,area,adress,type,purpose,flooPlan,url,lastUpdated,price,city
0,Eminent Apartment Of 2200 Sq Ft Is Vacant For ...,3,4,2200,"Block A, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"August 13, 2022",50000.0,Dhaka
1,"Apartment Ready To Rent In South Khulshi, Near...",3,4,1400,"South Khulshi, Khulshi, Chattogram",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/44...,https://www.bproperty.com/en/property/details-...,"January 25, 2022",30000.0,Chattogram
2,"Smartly priced 1950 SQ FT apartment, that you ...",3,4,1950,"Block F, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/11...,https://www.bproperty.com/en/property/details-...,"February 22, 2023",30000.0,Dhaka
3,2000 Sq Ft Residential Apartment Is Up For Ren...,3,3,2000,"Sector 9, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/14...,https://www.bproperty.com/en/property/details-...,"October 28, 2021",35000.0,Dhaka
4,Strongly Structured This 1650 Sq. ft Apartment...,3,4,1650,"Block I, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"February 19, 2023",25000.0,Dhaka
...,...,...,...,...,...,...,...,...,...,...,...,...
7552,"Picture Yourself, Residing In This Well Constr...",4,4,3600,"Sector 3, Uttara, Dhaka",Duplex,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",80000.0,Dhaka
7553,Flat For Rent In Uttara Sector 13 Near Lubana ...,3,2,900,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 9, 2022",19000.0,Dhaka
7554,1000 SQ FT flat for rent in Uttara Sector 13 n...,2,2,1000,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/12...,https://www.bproperty.com/en/property/details-...,"February 14, 2022",22000.0,Dhaka
7555,Well Planned Apartment For Rent In Gulshan 1 N...,3,4,3600,"Gulshan 1, Gulshan, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/30...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",175000.0,Dhaka
7556,An Apartment Is Ready For Rent At Baridhara DO...,4,4,2600,"Baridhara DOHS, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"November 22, 2021",90000.0,Dhaka

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7557 entries, 0 to 7556
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        7557 non-null   object
 1   beds         7557 non-null   int64
 2   bath         7557 non-null   int64
 3   area         7557 non-null   int64
 4   adress       7557 non-null   object
 5   type         7557 non-null   object
 6   purpose      7557 non-null   object
 7   flooPlan     7556 non-null   object
 8   url          7557 non-null   object
 9   lastUpdated  7557 non-null   object
 10  price        7557 non-null   float64
 11  city         7557 non-null   object
dtypes: float64(1), int64(3), object(8)
memory usage: 708.6+ KB

In [8]:
df['price'].mean()

np.float64(34079.02606854572)

In [9]:
df['price'].median()

19000.0

In [16]:
df.loc[df['city'] == 'Dhaka']

,title,beds,bath,area,adress,type,purpose,flooPlan,url,lastUpdated,price,city
0,Eminent Apartment Of 2200 Sq Ft Is Vacant For ...,3,4,2200,"Block A, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"August 13, 2022",50000.0,Dhaka
2,"Smartly priced 1950 SQ FT apartment, that you ...",3,4,1950,"Block F, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/11...,https://www.bproperty.com/en/property/details-...,"February 22, 2023",30000.0,Dhaka
3,2000 Sq Ft Residential Apartment Is Up For Ren...,3,3,2000,"Sector 9, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/14...,https://www.bproperty.com/en/property/details-...,"October 28, 2021",35000.0,Dhaka
4,Strongly Structured This 1650 Sq. ft Apartment...,3,4,1650,"Block I, Bashundhara R-A, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/10...,https://www.bproperty.com/en/property/details-...,"February 19, 2023",25000.0,Dhaka
5,"A nice residential flat of 3400 SQ FT, for ren...",5,5,3400,"Gulshan 1, Gulshan, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 14, 2023",110000.0,Dhaka
...,...,...,...,...,...,...,...,...,...,...,...,...
7552,"Picture Yourself, Residing In This Well Constr...",4,4,3600,"Sector 3, Uttara, Dhaka",Duplex,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",80000.0,Dhaka
7553,Flat For Rent In Uttara Sector 13 Near Lubana ...,3,2,900,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"February 9, 2022",19000.0,Dhaka
7554,1000 SQ FT flat for rent in Uttara Sector 13 n...,2,2,1000,"Sector 13, Uttara, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/12...,https://www.bproperty.com/en/property/details-...,"February 14, 2022",22000.0,Dhaka
7555,Well Planned Apartment For Rent In Gulshan 1 N...,3,4,3600,"Gulshan 1, Gulshan, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/30...,https://www.bproperty.com/en/property/details-...,"February 7, 2023",175000.0,Dhaka
7556,An Apartment Is Ready For Rent At Baridhara DO...,4,4,2600,"Baridhara DOHS, Dhaka",Apartment,For Rent,https://images-cdn.bproperty.com/thumbnails/15...,https://www.bproperty.com/en/property/details-...,"November 22, 2021",90000.0,Dhaka

In [11]:
df['city'].value_counts()

city
Dhaka         5332
Chattogram    2225
Name: count, dtype: int64

In [12]:
df['type'].value_counts()

type
Apartment    7489
Duplex         47
Building       21
Name: count, dtype: int64

In [27]:
# object wise split > function > combination
group_city = df.groupby(['city'])
group_city_type = df.groupby(['city','type'])

In [23]:
group_city['type'].value_counts(normalize=True).loc['Dhaka']

type
Apartment    0.988747
Duplex       0.007502
Building     0.003751
Name: proportion, dtype: float64

In [29]:
group_city_type['price'].agg(['mean', 'median'])

                               mean    median
city       type
Chattogram Apartment   19813.964817   16000.0
           Building    70000.000000   70000.0
           Duplex     105714.285714   60000.0
Dhaka      Apartment   35752.966616   20000.0
           Building   696500.000000  550000.0
           Duplex     259450.000000  135000.0

In [30]:
df_1['dataset'].value_counts()

dataset
Cleveland        304
Hungary          293
VA Long Beach    200
Switzerland      123
Name: count, dtype: int64

In [31]:
df_1['cp'].value_counts()

cp
asymptomatic       496
non-anginal        204
atypical angina    174
typical angina      46
Name: count, dtype: int64

How many people of each dataset in a region have the asymptomatic

In [34]:
df_1.groupby('dataset')['cp'].apply(lambda x: sum(x == 'asymptomatic'))

dataset
Cleveland        144
Hungary          123
Switzerland       98
VA Long Beach    131
Name: cp, dtype: int64